# Dependencies
markdown: kramdown

kramdown:
  input: GFM

pygments: false

# Permalinks
permalink: '/announcements/:title'

# Setup
title: OxyPlot
description: 'A cross-platform plotting library for .NET'
url: http://oxyplot.org

author:
  name: 'Oystein Bjorke'
  url: http://twitter.com/OysteinBjorke

paginate: 5
paginate_path: '/announcements/:num'

# Custom vars
version: 2014.1
forum: http://discussion.oxyplot.org/
nuget: http://www.nuget.org/packages?q=oxyplot
examples: http://resources.oxyplot.org/examplebrowser/
twitter: http://twitter.com/search?q=oxyplot
so : http://stackoverflow.com/questions/tagged/oxyplot?sort=newest

github:
  repo: http://github.com/oxyplot/oxyplot/
